### ISSUE TITLE
Bug: npm package is missing `dist` folder

### ISSUE THREAD

**Issue by JulianWowra** [droppedcode/typedoc-plugin-copy-assets#3]
The released versions `1.0.7` and `1.0.8` on NPM do not have a `dist` folder!

![Screenshot](https://github.com/droppedcode/typedoc-plugin-copy-assets/assets/36083682/7f87241c-ff6d-488c-b13b-d1c59d1baf65)
👀 [Take  a look](https://www.npmjs.com/package/@droppedcode/typedoc-plugin-copy-assets/v/1.0.8?activeTab=code)

**Comment by droppedcode** [comment]
Hi,

Thank you for reporting the issue.
I have uploaded a new version 1.0.9 that contains the dist folder.

Please check it out:
https://www.npmjs.com/package/@droppedcode/typedoc-plugin-copy-assets/v/1.0.9

If something still not ok, please reopen the ticket.
